work_dir: ./work_dir/prediction/jaad_tcnn_pose_gridflow
# weights: ./work_dir/reconstruction/kinetics/epoch50_model.pt

# feeder
feeder: feeder.feeder_prediction_jaad.Feeder
train_feeder_args:
  obs_len: 10
  pred_len: 10
  use_gt: True
  data_path: ../datasets/processed_data/prediction/jaad/train_data.pkl
  label_path: ../datasets/processed_data/prediction/jaad/train_metadata.pkl
test_feeder_args:
  obs_len: 10
  pred_len: 10
  use_gt: True
  data_path: ../datasets/processed_data/prediction/jaad/val_data.pkl
  label_path: ../datasets/processed_data/prediction/jaad/val_metadata.pkl


# model
model: net.tcnn_pose_gridflow.Model
model_args:
  obs_len: 10
  pred_len: 10
  loc_feats: 2
  pose_feats: 3
  num_keypoints: 18
  gridflow_feats: 24

# training
device: [0,1,2,3]
batch_size: 256 
test_batch_size: 256

# optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



