work_dir: ./work_dir/prediction/jaad/lstm/gt
weights:  ./work_dir/prediction/jaad/lstm/impute/epoch50_model.pt   # load weights from impute model

# feeder
feeder: feeder.feeder_prediction_jaad.Feeder
test_feeder_args:
  obs_len: 10
  pred_len: 10
  data_path: ../datasets/processed_data/prediction/jaad/val_data_gt.pkl
  label_path: ../datasets/processed_data/prediction/jaad/val_metadata_gt.pkl


# model
model: net.lstm.Model
model_args:
  obs_len: 10
  pred_len: 10
  loc_feats: 2
  pose_feats: 3
  num_keypoints: 18

# testing
phase: test
device: [0]
batch_size: 256 
test_batch_size: 256

# make sure to comment out self.load_optimizer()in prediction_settings.py
