work_dir: ./work_dir/prediction/jaad/impute

# feeder
feeder: feeder.feeder_prediction_jaad.Feeder
train_feeder_args:
  obs_len: 10
  pred_len: 10
  data_path: ../datasets/processed_data/prediction/jaad/train_data_impute.pkl
  label_path: ../datasets/processed_data/prediction/jaad/train_metadata_impute.pkl
test_feeder_args:
  obs_len: 10
  pred_len: 10
  data_path: ../datasets/processed_data/prediction/jaad/val_data_impute.pkl
  label_path: ../datasets/processed_data/prediction/jaad/val_metadata_impute.pkl


# model
model: net.lstm.Model
model_args:
  obs_len: 10
  pred_len: 10
  loc_feats: 2
  pose_feats: 3
  num_keypoints: 18

# training
device: [0]
batch_size: 256 
test_batch_size: 256

# optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



