work_dir: ./work_dir/prediction/jaad/const_vel/noisy

# feeder
feeder: feeder.feeder_prediction_jaad.Feeder
test_feeder_args:
  obs_len: 10
  pred_len: 10
  data_path: ../datasets/processed_data/prediction/jaad/val_data_noisy.pkl
  label_path: ../datasets/processed_data/prediction/jaad/val_metadata_noisy.pkl


# model
model: net.const_vel.Model
model_args:
  obs_len: 10
  pred_len: 10
  loc_feats: 2
  pose_feats: 3
  num_keypoints: 18

# testing
phase: test
device: [0]
batch_size: 256 
test_batch_size: 256

# make sure to comment out self.load_optimizer()in prediction_settings.py



