work_dir: /home/manhh/work_dir/reconstruction/kinetics
weights: /home/manhh/work_dir/recognition/kinetics/epoch50_model.pt

# feeder
feeder: feeder.feeder_reconstruction_kinetics.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 10 
  random_noise: True
  data_path: ../datasets/processed_data/reconstruction/kinetics/train_data.npy
  label_path: ../datasets/processed_data/reconstruction/kinetics/train_label.pkl
test_feeder_args:
  random_choose: False
  window_size: 10 
  random_noise: True
  data_path: ../datasets/processed_data/reconstruction/kinetics/val_data.npy
  label_path: ../datasets/processed_data/reconstruction/kinetics/val_label.pkl

# model
model: net.RecPoseNet.RecPoseNet
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True 
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0,1,2,3]
batch_size: 256 
test_batch_size: 256

# optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



