# command line: main.py prediction -c configurations/prediction/jaad/ours/train_noisy.yaml

H: 1080
W: 1080
base_lr: 0.1
batch_size: 256
config: configurations/prediction/jaad/ours/train_noisy.yaml
debug: false
device:
- 0
- 1
- 2
- 3
eval_interval: 1
feeder: feeder.feeder_prediction_jaad.Feeder
flow_feats: 24
ignore_weights:
- fcn
loc_feats: 3
log_interval: 100
model: net.pst_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    gridflow_feats: 24
    loc_feats: 2
    num_keypoints: 18
    obs_len: 10
    pose_feats: 3
    pred_len: 10
nesterov: true
num_epoch: 50
num_keypoints: 18
num_worker: 4
obs_len: 10
optimizer: SGD
pavi_log: false
phase: train
pose_feats: 3
pred_len: 10
print_log: true
save_interval: 10
save_log: true
save_result: false
start_epoch: 0
step:
- 20
- 30
- 40
- 50
test_batch_size: 256
test_feeder_args:
    data_path: ../datasets/processed_data/prediction/jaad/val_data_noisy.pkl
    label_path: ../datasets/processed_data/prediction/jaad/val_metadata_noisy.pkl
    obs_len: 10
    pred_len: 10
train_feeder_args:
    data_path: ../datasets/processed_data/prediction/jaad/train_data_noisy.pkl
    label_path: ../datasets/processed_data/prediction/jaad/train_metadata_noisy.pkl
    obs_len: 10
    pred_len: 10
use_gpu: true
weight_decay: 0.0001
weights: $HOME/work_dir/reconstruction/jaad/epoch50_model.pt
work_dir: $HOME/work_dir/prediction/jaad/ours/noisy
