work_dir: /home/manhh/work_dir/prediction/titan/lstm/noisy

# feeder
feeder: feeder.feeder_prediction_jaad.Feeder
train_feeder_args:
  obs_len: 10
  pred_len: 10
  data_path: ../datasets/processed_data/prediction/titan/train_data_noisy.pkl
  label_path: ../datasets/processed_data/prediction/titan/train_metadata_noisy.pkl
test_feeder_args:
  obs_len: 10
  pred_len: 10
  data_path: ../datasets/processed_data/prediction/titan/val_data_noisy.pkl
  label_path: ../datasets/processed_data/prediction/titan/val_metadata_noisy.pkl


# model
model: net.sota.lstm.Model
model_args:
  obs_len: 10
  pred_len: 10
  loc_feats: 2
  pose_feats: 3
  num_keypoints: 18

# training
device: [0]
batch_size: 256
test_batch_size: 256

# optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



